identities:
  name: Brendan Ingham
  personal:
    email: brendan@ingham.dev
    bw_id: "b4292ecb-c0aa-4ae4-8f0a-b284017a86ac"
  work:
    email: brendan.ingham@clickdealer.co.uk
    bw_id: "c6b87e57-a43e-47bc-8502-b2800089be8b"

packages:
  common:
    - glow
    - bat
    - fzf
    - mise
    - starship
    - atuin
    - direnv
    - lsd
    - neovim
    - topgrade
    - wget
    - fish
    - lazygit
  darwin:
    - bash
    - gh
    - git-delta
  darwin-homebrew:
    - ghostty
    - google-chrome
    - discord
    - spotify
    - postman
    - font-maple-mono
    - font-maple-mono-nf
    - zed
    - zen
  linux:
    - flatpak
    - meld
    - actionlint
    - shellcheck
    - gnupg
    - go
    - maplemono-nf
    - github-cli
  linux-flatpak:
    - dev.zed.Zed
    - com.discordapp.Discord
    - com.spotify.Client
    - org.videolan.VLC
    - org.deskflow.deskflow
  mise:
    node: "24"
    npm: "11.8.0"
    npm:@bitwarden/cli: "latest"
    npm:@google/gemini-cli: "latest"
    npm:eslint: "latest"
    npm:typescript: "latest"
